### ISSUE TITLE
README documents a "-f" flag that doesn't exist

### ISSUE THREAD

**Issue by palfrey** [TGotwig/vidmerger#2]
I'm assuming it's a alias for "--format", but it doesn't work with current master (4d0938470c00330e67cd09a79d5663e3260f5136)

**Comment by palfrey** [comment]
Nope, my mistake. It does support it, just not listed when you give it the wrong args
```
palfrey@weizen:[~/src/vidmerger] cargo run -- -f foo                                                                                                                 <=====
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/vid_merger -f foo`
error: The following required arguments were not provided:
    <DIR>
    --format <format>

USAGE:
    vid_merger <DIR> --format <format>

For more information try --help
```

**Comment by TGotwig** [comment]
Hey palfrey and thanks for your contribution 🙋‍♂️

Yeah right, you can also run `cargo run -- --help` for printing a little bit more out,
working on the readme 👷‍♂️
