### ISSUE TITLE
Lack of format docs/logging

### ISSUE THREAD

**Issue by palfrey** [TGotwig/vidmerger#3]
So I tried doing `cargo run -- -f foo target` just as a "let's see how it copes" test (I know it'll fail, but was hoping for logging info detailing what was wrong) and got the following

```
Order of merging 👇



stderr: dyld: Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /usr/local/opt/p11-kit/lib/libp11-kit.0.dylib
  Reason: image not found

Something went wrong 😖
```

No idea what happened there! Thoughts?

**Comment by TGotwig** [comment]
I think this is an MacOS issue which I had a few months ago,
does `brew install libffi` help?

Seems you also have no videos with the extention `foo`,
you can run `make prepare` to load two videos over `youtube-dl` with the extension `mp4` 🎞

**Comment by palfrey** [comment]
I think the biggest problem I had here was that I have no idea what caused the error. A initial naive approach would assume this was something up with vidmerger, but the correct answer is that ffmpeg is a bit broken. However, from that error message I can't tell the difference. Possibly useful to print the command that failed before dumping the output from said command?

**Comment by TGotwig** [comment]
Yeah sounds good 😃👍
