### ISSUE TITLE
Make Build fails on Ubuntu

### ISSUE THREAD

**Issue by Jalawoud** [TGotwig/vidmerger#9]
Im pretty clueless with things if they don't come in an exe format or sudo apt get so please bear with me.  I have ffmpeg installed, I downloaded the zip and extracted it to my desktop. Next the readme says "Run make build to build for Mac, Linux and Windows." 

When I run make build it automatically tries to build it for MacOS and not linux. Which results in a fail. error code 2, Could someone enlighten me on what im doing wrong?

**Comment by Jalawoud** [comment]
After messing around and making sure I have all reqs installed, I have gotten 
"Successfully generated 'output.mp4'! 😆🎞" to appear, however after opening a terminal in the folder vidmerger-master and running "vidmerger" it says command not found.

**Comment by TGotwig** [comment]
Hello Jalawoud 🙋‍♂️
I guess you just want to download and run the program?
Then download it from here 👉 https://github.com/TGotwig/vidmerger/releases/tag/v0.1.1
```
wget https://github.com/TGotwig/vidmerger/releases/download/v0.1.1/vidmerger-linux.tar.gz
```
Extract it:
```
tar xf vidmerger-linux.tar.gz
```
Use the binary 🙂
```
./vidmerger --help
``` 
Unfortunately it's not so easy to make it available at snapcraft and chocolatey but I'm working on that 👨‍🔧

**Comment by Jalawoud** [comment]
Thank you so much, such a helpful and responsive owner, works great now. 

I do have another question though, does this support files which have different widths/heights/encodes? Those seem to be the only outputs that are not playing properly within the output file.

**Comment by TGotwig** [comment]
Cool that it works for you now 👍

Perhaps another ticket would be good, regarding the other points.
